### ISSUE TITLE
theme dark light 是不是搞反了？

### ISSUE THREAD

**Issue by llt22** [bearice/RustCat#1]
为什么 dark 是 白色的 icon?

**Comment by bearice** [comment]
没有哦,
dark theme代表背景色是深色,所以图标就是白色
light theme正相反

**Comment by llt22** [comment]
> 没有哦, dark theme代表背景色是深色,所以图标就是白色 light theme正相反

在只有一个图标就是主要界面的软件上，我一时没反应过来
