### ISSUE TITLE
这个cpu使用率计算是不是不正确

### ISSUE THREAD

**Issue by KnightBlood** [bearice/RustCat#7]
![image](https://github.com/bearice/RustCat/assets/14256591/57c12d61-2322-4d73-b280-c33021ea4c0c)

**Comment by bearice** [comment]
![Screenshot 2024-06-20 165801](https://github.com/bearice/RustCat/assets/270121/03273624-7bdb-4173-beea-dc3ba905a270)

任务管理器里计算CPU利用率
的方式似乎是不一样的，用 [process explorer](https://learn.microsoft.com/en-us/sysinternals/downloads/process-explorer) 看到的利用率就很相似了。

**Comment by bearice** [comment]
FYI: https://www.reddit.com/r/Windows10/comments/zxhfzr/why_the_cpu_usage_value_is_different_between/
